# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9ee9bfe1a6d5e2027a33bd2b630006a9d041f21388873301d874889efae651ee6cdf164db00d8ce95c1ded48bef95ca7bf0cb537bb607f130b87861a13bbb30

test:
  secret_key_base: 8bb997a9fdbeb6071fb124bf4c311194af3131ebd85476425ac9ab6f7f70f0e2c3c327346da4a2385108ca08902a871922f8c9c51d852954cd819c3e952a4ac2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
